MyStatTagHelpers/MyStatTagHelpers/Models/ErrorViewModel.cs
namespace MyStatTagHelpers.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyStatTagHelpers/MyStatTagHelpers/Models/HomeWork.cs
using System.ComponentModel.DataAnnotations;

namespace MyStatTagHelpers.Models
{
    public class HomeWork
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(450)]
        public string Title { get; set; }
        public DateTime CreatedDate { get; set; }
        public string File { get; set; }

    }
}

MyStatTagHelpers/MyStatTagHelpers/Models/User.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyStatTagHelpers.Models
{
    [Index("Name", IsUnique = true)]
    public class User
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(450)]

        public string Name { get; set; }
        [MaxLength(450)]
        public string? Surname { get; set; }
        [PasswordPropertyText]
        public string Password { get; set; }

    }
}

MyStatTagHelpers/MyStatTagHelpers/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyStatTagHelpers.Models;
using System.Diagnostics;

namespace MyStatTagHelpers.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyStatTagHelpers/MyStatTagHelpers/Controllers/HomeWorkController.cs
using Microsoft.AspNetCore.Mvc;
using MyStatTagHelpers.Models;
using MyStatTagHelpers.Services;
using System.IO;
using System.Text;

namespace MyStatTagHelpers.Controllers
{
    public class HomeWorkController : Controller
    {
        private readonly IHomeWorkManager _homeWorkManager;
        private readonly List<HomeWork> _homeWorks = new List<HomeWork>();

        public HomeWorkController(IHomeWorkManager homeWorkManager)
        {
            _homeWorkManager = homeWorkManager;

            _homeWorks = _homeWorkManager.GetHomeWorks();
        }

        public async Task<IActionResult> Index()
        {

            return View(await _homeWorkManager.GetHomeWorksAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Add([FromBody] HomeWork? hw)
        {

            if (hw == null)
            {
                return BadRequest();
            }

            try
            {
                hw.CreatedDate = DateTime.Now;

                await _homeWorkManager.AddHomeWorkAsync(hw);
                return Ok();
            }
            catch
            {
                return BadRequest();
            }
        }

        [HttpGet]
        [ActionName("Add")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Download(int id )
        {
                      
            string contentType = "application/txt";
           var l= await _homeWorkManager.GetHomeWorkByIdAsync(id);
            byte[] bytes = Encoding.UTF8.GetBytes(l.File);
            return File(bytes, contentType, $"{l.Title}.txt");
        }

        [HttpPost]
        public async Task<IActionResult> Remove([FromBody] HomeWork? hw)
        {
            if (hw == null)
            {
                return BadRequest();
            }

            var target = _homeWorks.Find(c => c.Id == hw.Id);

            if (target != null)
            {
                _homeWorks.Remove(target);
                await _homeWorkManager.RemoveHomeWorkAsync(hw.Id);

                return Ok();
            }

            return BadRequest();

        }
    }
}

MyStatTagHelpers/MyStatTagHelpers/Views/HomeWork/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


@section Scripts
{
    <script src="~/js/homework-add.js"></script>
}

<div>Title</div>
<input id="model-title" type="text" placeholder="Title"/>
<div>File</div>
<input  id="model-description" type="text" placeholder="Text"/>
<input id="button-add" type="button" value="Add"/>

MyStatTagHelpers/MyStatTagHelpers/Views/HomeWork/Index.cshtml
@using MyStatTagHelpers.Models
@using MyStatTagHelpers.HtmlHelpers
@*
*@
@model List<HomeWork>
@{
}
@section Scripts
    {
    <script src="~/js/homework-remove.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />
}

<homework homework-list="Model"></homework>

   @* @Html.RenderHomeWorks(Model);
*@

MyStatTagHelpers/MyStatTagHelpers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyStatTagHelpers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyStatTagHelpers.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyStatTagHelpers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HomeWork" asp-action="Index">HomeWorks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HomeWork" asp-action="Add">AddHomeWork</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyStatTagHelpers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>